name: your_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Menurunkan versi minimum SDK untuk kompatibilitas lebih baik

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  math_expressions: ^2.3.1
  shared_preferences: ^2.2.0
  intl: ^0.18.0
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Menurunkan versi untuk menghindari konflik

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.jpg
    - assets/images/igs_logo.jpeg
    - assets/images/guitar_bg.jpeg
    - assets/images/us_flag.jpeg
    - assets/images/gitar1.jpeg
    - assets/images/gitar2.jpeg
    - assets/images/yamaha_f310.jpeg
    - assets/images/yamaha_f310_detail1.jpeg
    - assets/images/yamaha_f310_detail2.jpeg
    - assets/images/yamaha_f310_detail3.jpeg
    - assets/images/fender_strat.jpeg
    - assets/images/fender_strat_detail1.jpeg
    - assets/images/fender_strat_detail2.jpeg
    - assets/images/fender_strat_detail3.jpeg

  # Uncomment jika diperlukan:
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700